/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsIdRouteImport } from './routes/patients.$id'
import { Route as PatientsIdIndexRouteImport } from './routes/patients.$id.index'
import { Route as PatientsNewUploadRouteImport } from './routes/patients.new.upload'
import { Route as PatientsNewManualRouteImport } from './routes/patients.new.manual'
import { Route as PatientsIdUploadRouteImport } from './routes/patients.$id.upload'
import { Route as PatientsIdReconcileRouteImport } from './routes/patients.$id.reconcile'
import { Route as PatientsIdNarrativeRouteImport } from './routes/patients.$id.narrative'
import { Route as PatientsIdCallsRouteImport } from './routes/patients.$id.calls'

const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdIndexRoute = PatientsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsNewUploadRoute = PatientsNewUploadRouteImport.update({
  id: '/new/upload',
  path: '/new/upload',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsNewManualRoute = PatientsNewManualRouteImport.update({
  id: '/new/manual',
  path: '/new/manual',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsIdUploadRoute = PatientsIdUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdReconcileRoute = PatientsIdReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdNarrativeRoute = PatientsIdNarrativeRouteImport.update({
  id: '/narrative',
  path: '/narrative',
  getParentRoute: () => PatientsIdRoute,
} as any)
const PatientsIdCallsRoute = PatientsIdCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => PatientsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patients': typeof PatientsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/calls': typeof PatientsIdCallsRoute
  '/patients/$id/narrative': typeof PatientsIdNarrativeRoute
  '/patients/$id/reconcile': typeof PatientsIdReconcileRoute
  '/patients/$id/upload': typeof PatientsIdUploadRoute
  '/patients/new/manual': typeof PatientsNewManualRoute
  '/patients/new/upload': typeof PatientsNewUploadRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/patients': typeof PatientsIndexRoute
  '/patients/$id/calls': typeof PatientsIdCallsRoute
  '/patients/$id/narrative': typeof PatientsIdNarrativeRoute
  '/patients/$id/reconcile': typeof PatientsIdReconcileRoute
  '/patients/$id/upload': typeof PatientsIdUploadRoute
  '/patients/new/manual': typeof PatientsNewManualRoute
  '/patients/new/upload': typeof PatientsNewUploadRoute
  '/patients/$id': typeof PatientsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patients': typeof PatientsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sync': typeof SyncRoute
  '/patients/$id': typeof PatientsIdRouteWithChildren
  '/patients/': typeof PatientsIndexRoute
  '/patients/$id/calls': typeof PatientsIdCallsRoute
  '/patients/$id/narrative': typeof PatientsIdNarrativeRoute
  '/patients/$id/reconcile': typeof PatientsIdReconcileRoute
  '/patients/$id/upload': typeof PatientsIdUploadRoute
  '/patients/new/manual': typeof PatientsNewManualRoute
  '/patients/new/upload': typeof PatientsNewUploadRoute
  '/patients/$id/': typeof PatientsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patients'
    | '/settings'
    | '/sync'
    | '/patients/$id'
    | '/patients/'
    | '/patients/$id/calls'
    | '/patients/$id/narrative'
    | '/patients/$id/reconcile'
    | '/patients/$id/upload'
    | '/patients/new/manual'
    | '/patients/new/upload'
    | '/patients/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/sync'
    | '/patients'
    | '/patients/$id/calls'
    | '/patients/$id/narrative'
    | '/patients/$id/reconcile'
    | '/patients/$id/upload'
    | '/patients/new/manual'
    | '/patients/new/upload'
    | '/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/patients'
    | '/settings'
    | '/sync'
    | '/patients/$id'
    | '/patients/'
    | '/patients/$id/calls'
    | '/patients/$id/narrative'
    | '/patients/$id/reconcile'
    | '/patients/$id/upload'
    | '/patients/new/manual'
    | '/patients/new/upload'
    | '/patients/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SyncRoute: typeof SyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id/': {
      id: '/patients/$id/'
      path: '/'
      fullPath: '/patients/$id/'
      preLoaderRoute: typeof PatientsIdIndexRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/new/upload': {
      id: '/patients/new/upload'
      path: '/new/upload'
      fullPath: '/patients/new/upload'
      preLoaderRoute: typeof PatientsNewUploadRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/new/manual': {
      id: '/patients/new/manual'
      path: '/new/manual'
      fullPath: '/patients/new/manual'
      preLoaderRoute: typeof PatientsNewManualRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$id/upload': {
      id: '/patients/$id/upload'
      path: '/upload'
      fullPath: '/patients/$id/upload'
      preLoaderRoute: typeof PatientsIdUploadRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/reconcile': {
      id: '/patients/$id/reconcile'
      path: '/reconcile'
      fullPath: '/patients/$id/reconcile'
      preLoaderRoute: typeof PatientsIdReconcileRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/narrative': {
      id: '/patients/$id/narrative'
      path: '/narrative'
      fullPath: '/patients/$id/narrative'
      preLoaderRoute: typeof PatientsIdNarrativeRouteImport
      parentRoute: typeof PatientsIdRoute
    }
    '/patients/$id/calls': {
      id: '/patients/$id/calls'
      path: '/calls'
      fullPath: '/patients/$id/calls'
      preLoaderRoute: typeof PatientsIdCallsRouteImport
      parentRoute: typeof PatientsIdRoute
    }
  }
}

interface PatientsIdRouteChildren {
  PatientsIdCallsRoute: typeof PatientsIdCallsRoute
  PatientsIdNarrativeRoute: typeof PatientsIdNarrativeRoute
  PatientsIdReconcileRoute: typeof PatientsIdReconcileRoute
  PatientsIdUploadRoute: typeof PatientsIdUploadRoute
  PatientsIdIndexRoute: typeof PatientsIdIndexRoute
}

const PatientsIdRouteChildren: PatientsIdRouteChildren = {
  PatientsIdCallsRoute: PatientsIdCallsRoute,
  PatientsIdNarrativeRoute: PatientsIdNarrativeRoute,
  PatientsIdReconcileRoute: PatientsIdReconcileRoute,
  PatientsIdUploadRoute: PatientsIdUploadRoute,
  PatientsIdIndexRoute: PatientsIdIndexRoute,
}

const PatientsIdRouteWithChildren = PatientsIdRoute._addFileChildren(
  PatientsIdRouteChildren,
)

interface PatientsRouteChildren {
  PatientsIdRoute: typeof PatientsIdRouteWithChildren
  PatientsIndexRoute: typeof PatientsIndexRoute
  PatientsNewManualRoute: typeof PatientsNewManualRoute
  PatientsNewUploadRoute: typeof PatientsNewUploadRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsIdRoute: PatientsIdRouteWithChildren,
  PatientsIndexRoute: PatientsIndexRoute,
  PatientsNewManualRoute: PatientsNewManualRoute,
  PatientsNewUploadRoute: PatientsNewUploadRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientsRoute: PatientsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
